# Generated by Django 2.1.7 on 2020-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
        ('account', '0002_remove_account_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(to='play.Play'),
        ),
    ]
