# Generated by Django 2.1.7 on 2020-02-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0005_remove_seat_selected'),
        ('order', '0009_order_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seats',
            field=models.ManyToManyField(to='seat.Seat'),
        ),
    ]
