# Generated by Django 2.1.7 on 2020-02-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_schedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
