# Generated by Django 2.1.7 on 2020-01-30 06:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
