# Generated by Django 2.1.7 on 2020-02-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_play_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
